# Generated by Django 3.2 on 2023-02-08 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230204_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='id_expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='id_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('s', 'Single'), ('m', 'Married')], max_length=2),
        ),
        migrations.AddField(
            model_name='account',
            name='means_of_id',
            field=models.CharField(blank=True, choices=[('nid', 'national id card'), ('dl', 'driver licence'), ('vc', 'Voters Card'), ('ip', 'International Passport')], default='savings', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='next_of_kin_contact',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='account',
            name='next_of_kin_dob',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='next_of_kin_title',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='account',
            name='next_of_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='account',
            name='religion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='BlockedTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.account')),
            ],
        ),
    ]
