# Generated by Django 3.2 on 2023-02-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_account_means_of_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='next_of_name',
            new_name='next_of_kin_name',
        ),
    ]
