# Generated by Django 3.2 on 2023-02-08 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_otheraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='otheraccount',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
