# Generated by Django 3.2 on 2023-02-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transfer_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='next_of_kin_dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
