# Generated by Django 3.2 on 2023-02-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230211_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='sent_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='core.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sent_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receives', to='core.account'),
        ),
    ]
