# Generated by Django 3.2 on 2023-02-16 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230212_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
